ALTER TABLE DISPATCH
	ADD CONSTRAINT FK_DISPATCH
	FOREIGN KEY (OWNER)
	REFERENCES CLIENT (NIT);

ALTER TABLE INVOICE
	ADD CONSTRAINT FK_INVOICE
	FOREIGN KEY (CLIENT)
	REFERENCES CLIENT (NIT);

ALTER TABLE ITEM_PRICE
	ADD CONSTRAINT FK_ITEM_PRICE
	FOREIGN KEY (ITEM)
	REFERENCES ITEM (ITEM_CODE);

ALTER TABLE ORDER_DETAIL
	ADD CONSTRAINT FK_ORDER_TO_INVOICE
	FOREIGN KEY (INVOICE)
	REFERENCES INVOICE (SERIAL_NUMBER);

ALTER TABLE ORDER_DETAIL
	ADD CONSTRAINT FK_ORDER_TO_ITEM
	FOREIGN KEY (DETAIL_ITEM)
	REFERENCES ITEM (ITEM_CODE);
	
